// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace secureshare.Models;

public partial class Action
{
    [Key]
    public int ActionID { get; set; }

    public int? UserID { get; set; }

    [StringLength(50)]
    public string ActionPerformed { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Timestamp { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("Actions")]
    public virtual User User { get; set; }
}