// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace secureshare.Models;

public partial class Admin
{
    [Key]
    public int AdminID { get; set; }

    [StringLength(255)]
    public string Username { get; set; }

    [StringLength(255)]
    public string Password { get; set; }
}