// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace secureshare.Models;

public partial class Branch
{
    [Key]
    public int BranchId { get; set; }

    [StringLength(100)]
    public string BranchName { get; set; }
}