// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace secureshare.Models;

public partial class Folder
{
    [Key]
    public int FolderID { get; set; }

    [StringLength(1024)]
    public string FolderPath { get; set; }

    public string Name { get; set; }

    public int? FileCount { get; set; }

    public int? PartitionID { get; set; }

    [ForeignKey("PartitionID")]
    [InverseProperty("Folders")]
    public virtual Partition Partition { get; set; }

    [InverseProperty("Folder")]
    public virtual ICollection<UserFolderPermission> UserFolderPermissions { get; set; } = new List<UserFolderPermission>();
}