// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace secureshare.Models;

public partial class User
{
    [Key]
    public int UserID { get; set; }

    [StringLength(255)]
    public string Username { get; set; }

    public int? DepartmentID { get; set; }

    [StringLength(255)]
    public string Password { get; set; }

    public int? PermissionType { get; set; }

    public int? BranchID { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();

    [InverseProperty("User")]
    public virtual ICollection<UserFolderPermission> UserFolderPermissions { get; set; } = new List<UserFolderPermission>();
}