// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace secureshare.Models;

public partial class UserFolderPermission
{
    [Key]
    public int ID { get; set; }

    public int? UserID { get; set; }

    public int? FolderID { get; set; }

    [ForeignKey("FolderID")]
    [InverseProperty("UserFolderPermissions")]
    public virtual Folder Folder { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserFolderPermissions")]
    public virtual User User { get; set; }
}